server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.178.235.51:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    format_sql: true

  security:
    oauth2:
      client:
        registration:
#          kakao:
#            client-id: 발급받은 client-id key
#            client-secret: 발급받은 client-secret key
          google:
            client-id: 338703056971-n02tt0hd5dcegs2q94lm4m0u2p1g505g.apps.googleusercontent.com
            client-secret: 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
#          naver:
#            client-id: 발급받은 client-id key
#            client-secret: 발급받은 client-secret key
#          facebook:
#            client-id: 발급받은 client-id key
#            client-secret: 발급받은 client-secret key

